version: "3.8"

services:
  vpn:
    container_name: vpn
    privileged: true
    restart: always
    image: liskeee/sac-vpn-proxy
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    devices:
      - /dev/bus/usb/001/002:/dev/bus/usb/001/002
    ports:
      - "8889:8889"
    # optional
    # volumes:
    #   - ./ssh_config:/root/.ssh/config_template
